// AUTO-GENERATED by scripts/generate-svg-sprite.mjs – DO NOT EDIT MANUALLY
// Re-run: node scripts/generate-svg-sprite.mjs  (or via npm run build / npm start)

export interface SvgSymbolMeta {
  viewBox: string;
  /** Original SVG width attribute (e.g. "35.28mm"). null if not present. */
  width: string | null;
  /** Original SVG height attribute (e.g. "52.92mm"). null if not present. */
  height: string | null;
}

export const SVG_SPRITE_META: Record<string, SvgSymbolMeta> = {
  "about-bubble": {
    "viewBox": "0 0 181.91 73.49",
    "width": "64.18mm",
    "height": "25.93mm"
  },
  "about-buddha": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-coffee": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-dino": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-divider": {
    "viewBox": "0 0 595.28 41.67",
    "width": "210mm",
    "height": "14.7mm"
  },
  "about-family": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-iced_coffee": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-lama": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-lock": {
    "viewBox": "0 0 100 100",
    "width": "35.28mm",
    "height": "35.28mm"
  },
  "about-move": {
    "viewBox": "0 0 100 100",
    "width": "35.28mm",
    "height": "35.28mm"
  },
  "about-notebook_off": {
    "viewBox": "0 0 200 200",
    "width": "70.56mm",
    "height": "70.56mm"
  },
  "about-notebook_on": {
    "viewBox": "0 0 200 200",
    "width": "70.56mm",
    "height": "70.56mm"
  },
  "about-paper_garbage": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-pencils": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-polaroid": {
    "viewBox": "0 0 282.98 342.25",
    "width": "99.83mm",
    "height": "120.74mm"
  },
  "about-shiba_photo": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-treetrunks": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "about-vase": {
    "viewBox": "0 0 100 150",
    "width": "35.28mm",
    "height": "52.92mm"
  },
  "contact-bubble": {
    "viewBox": "0 0 181.91 73.49",
    "width": "64.18mm",
    "height": "25.93mm"
  },
  "contact-letter": {
    "viewBox": "0 0 28.89 25.08",
    "width": "10.19mm",
    "height": "8.85mm"
  },
  "contact-polaroid": {
    "viewBox": "0 0 282.98 342.25",
    "width": "99.83mm",
    "height": "120.74mm"
  },
  "logos-logo_github": {
    "viewBox": "0 0 100 100",
    "width": "100",
    "height": "100"
  },
  "logos-logo_insta": {
    "viewBox": "0 0 100 100",
    "width": "100",
    "height": "100"
  },
  "logos-logo_itch": {
    "viewBox": "0 0 100 100",
    "width": "100",
    "height": "100"
  },
  "logos-logo_linkedin": {
    "viewBox": "0 0 100 100",
    "width": "100",
    "height": "100"
  },
  "logos-logo_x": {
    "viewBox": "0 0 100 100",
    "width": "100",
    "height": "100"
  },
  "not-found-404": {
    "viewBox": "0 0 520.34 432.55",
    "width": "183.57mm",
    "height": "152.6mm"
  },
  "name": {
    "viewBox": "0 0 398.13 16.38",
    "width": "140.45mm",
    "height": "5.78mm"
  }
};
